# Generated by Django 5.1.4 on 2026-08-07 02:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, default='Untitled Stream', max_length=200)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('live', 'Live'), ('ended', 'Ended'), ('error', 'Error')], default='idle', max_length=10)),
                ('ai_character', models.CharField(default='default_avatar', max_length=100)),
                ('background', models.CharField(default='none', max_length=100)),
                ('quality', models.CharField(choices=[('low', 'Low (fast)'), ('medium', 'Medium'), ('high', 'High'), ('ultra', 'Ultra (4K)')], default='medium', max_length=10)),
                ('resolution', models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('4k', '4K')], default='720p', max_length=10)),
                ('camera_device', models.CharField(blank=True, default='', max_length=150)),
                ('microphone_device', models.CharField(blank=True, default='', max_length=150)),
                ('mirrored', models.BooleanField(default=False)),
                ('muted', models.BooleanField(default=False)),
                ('audience_count', models.PositiveIntegerField(default=0)),
                ('peak_audience', models.PositiveIntegerField(default=0)),
                ('credits_used', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
