# Generated by Django 5.1.4 on 2026-08-07 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebRTCSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('offered', 'Offered'), ('answered', 'Answered'), ('connected', 'Connected'), ('closed', 'Closed')], default='pending', max_length=12)),
                ('offer_sdp', models.TextField(blank=True, default='')),
                ('answer_sdp', models.TextField(blank=True, default='')),
                ('broadcaster_ice', models.JSONField(blank=True, default=list)),
                ('viewer_ice', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webrtc_sessions', to='studio.stream')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
