# Generated by Django 5.1.4 on 2026-08-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='obs_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
