# Generated by Django 5.1.4 on 2026-08-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_obs_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_active_access',
            field=models.BooleanField(default=False),
        ),
    ]
