# Generated by Django 5.1.4 on 2026-08-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_creditplan_paymentmethod_platformsetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='support_telegram_username',
            field=models.CharField(blank=True, default='', help_text='Telegram username only, e.g. supportcreoveya or @supportcreoveya.', max_length=255),
        ),
    ]
